-- Esquema del Sistema de Ventas para PostgreSQL (Supabase).
-- Lo ejecuta ConexionBD al conectarse; es idempotente (se puede correr siempre).
-- Mismas tablas y columnas que la version SQLite, para que los DAO funcionen igual.

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS categorias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    descripcion TEXT
);

CREATE TABLE IF NOT EXISTS productos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    precio NUMERIC(12, 2) NOT NULL,
    existencia INTEGER NOT NULL DEFAULT 0,
    categoria_id INTEGER REFERENCES categorias(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS clientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nit TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    direccion TEXT,
    telefono TEXT
);

CREATE TABLE IF NOT EXISTS empleados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_empleado TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    nit TEXT,
    telefono TEXT,
    puesto TEXT
);

CREATE TABLE IF NOT EXISTS proveedores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nit TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    direccion TEXT,
    telefono TEXT,
    correo TEXT
);

CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    clave_hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    rol TEXT NOT NULL CHECK (rol IN ('ADMINISTRADOR', 'VENDEDOR')),
    activo INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS facturas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_factura TEXT NOT NULL UNIQUE,
    nit TEXT NOT NULL,
    cliente TEXT NOT NULL,
    fecha TEXT NOT NULL,
    total NUMERIC(12, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS factura_detalles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id INTEGER NOT NULL REFERENCES facturas(id) ON DELETE CASCADE,
    producto TEXT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio NUMERIC(12, 2) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    producto_id INTEGER REFERENCES productos(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS compras (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_compra TEXT NOT NULL UNIQUE,
    proveedor_id INTEGER NOT NULL REFERENCES proveedores(id),
    usuario_id INTEGER REFERENCES usuarios(id) ON DELETE SET NULL,
    fecha TEXT NOT NULL,
    total NUMERIC(12, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS compra_detalles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id INTEGER NOT NULL REFERENCES compras(id) ON DELETE CASCADE,
    producto_id INTEGER NOT NULL REFERENCES productos(id),
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    costo_unitario NUMERIC(12, 2) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL
);

-- Sesiones de la app movil: token temporal que se entrega al iniciar sesion.
CREATE TABLE IF NOT EXISTS sesiones_app (
    token UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    creada TIMESTAMPTZ NOT NULL DEFAULT now(),
    expira TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_factura_detalles_factura ON factura_detalles (factura_id);
CREATE INDEX IF NOT EXISTS idx_compra_detalles_compra ON compra_detalles (compra_id);
CREATE INDEX IF NOT EXISTS idx_sesiones_app_usuario ON sesiones_app (usuario_id);

-- ---------------------------------------------------------------------------
-- Seguridad para la API publica de Supabase (la usa la app movil).
-- RLS activo y sin politicas: nadie puede leer ni escribir las tablas por la
-- API. La app de escritorio entra con el usuario duenio de las tablas, al que
-- RLS no le aplica. La app movil solo puede ejecutar las funciones app_*,
-- que validan el token de sesion.
-- ---------------------------------------------------------------------------
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE empleados ENABLE ROW LEVEL SECURITY;
ALTER TABLE proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE facturas ENABLE ROW LEVEL SECURITY;
ALTER TABLE factura_detalles ENABLE ROW LEVEL SECURITY;
ALTER TABLE compras ENABLE ROW LEVEL SECURITY;
ALTER TABLE compra_detalles ENABLE ROW LEVEL SECURITY;
ALTER TABLE sesiones_app ENABLE ROW LEVEL SECURITY;

DO $bloque$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
        REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
    END IF;
END
$bloque$;

-- Devuelve el id del usuario duenio del token, o lanza error si no es valido.
CREATE OR REPLACE FUNCTION app_usuario_de(p_token UUID) RETURNS INTEGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
DECLARE
    v_id INTEGER;
BEGIN
    SELECT s.usuario_id INTO v_id
    FROM sesiones_app s JOIN usuarios u ON u.id = s.usuario_id
    WHERE s.token = p_token AND s.expira > now() AND u.activo = 1;
    IF v_id IS NULL THEN
        RAISE EXCEPTION 'Sesión inválida o vencida. Inicie sesión de nuevo.' USING ERRCODE = '28000';
    END IF;
    RETURN v_id;
END
$fn$;

-- Inicio de sesion con los mismos usuarios del sistema de escritorio (hash bcrypt).
CREATE OR REPLACE FUNCTION app_login(p_usuario TEXT, p_clave TEXT) RETURNS JSON
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions AS $fn$
DECLARE
    u usuarios%ROWTYPE;
    v_token UUID;
BEGIN
    SELECT * INTO u FROM usuarios WHERE lower(usuario) = lower(trim(p_usuario));
    -- chr(36) = '$': los hash bcrypt empiezan con $2 (los antiguos PBKDF2 no se pueden verificar aqui)
    IF u.id IS NULL OR u.activo <> 1 OR u.clave_hash NOT LIKE chr(36) || '2%'
            OR u.clave_hash <> crypt(p_clave, u.clave_hash) THEN
        PERFORM pg_sleep(1);  -- frena los intentos de adivinar contrasenas
        RAISE EXCEPTION 'Usuario o contraseña incorrectos.' USING ERRCODE = '28P01';
    END IF;
    DELETE FROM sesiones_app WHERE expira < now();
    INSERT INTO sesiones_app (usuario_id, expira) VALUES (u.id, now() + INTERVAL '8 hours')
    RETURNING token INTO v_token;
    RETURN json_build_object('token', v_token, 'nombre', u.nombre, 'rol', u.rol);
END
$fn$;

CREATE OR REPLACE FUNCTION app_logout(p_token UUID) RETURNS VOID
LANGUAGE sql SECURITY DEFINER SET search_path = public AS $fn$
    DELETE FROM sesiones_app WHERE token = p_token;
$fn$;

CREATE OR REPLACE FUNCTION app_productos(p_token UUID, p_buscar TEXT DEFAULT '')
RETURNS TABLE (codigo TEXT, nombre TEXT, categoria TEXT, precio NUMERIC, existencia INTEGER)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
#variable_conflict use_column
BEGIN
    PERFORM app_usuario_de(p_token);
    RETURN QUERY
        SELECT p.codigo, p.nombre, c.nombre, p.precio, p.existencia
        FROM productos p LEFT JOIN categorias c ON c.id = p.categoria_id
        WHERE coalesce(p_buscar, '') = ''
           OR p.codigo ILIKE '%' || p_buscar || '%'
           OR p.nombre ILIKE '%' || p_buscar || '%'
        ORDER BY p.nombre
        LIMIT 200;
END
$fn$;

CREATE OR REPLACE FUNCTION app_clientes(p_token UUID, p_buscar TEXT DEFAULT '')
RETURNS TABLE (nit TEXT, nombre TEXT, direccion TEXT, telefono TEXT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
#variable_conflict use_column
BEGIN
    PERFORM app_usuario_de(p_token);
    RETURN QUERY
        SELECT c.nit, c.nombre, c.direccion, c.telefono
        FROM clientes c
        WHERE coalesce(p_buscar, '') = ''
           OR c.nit ILIKE '%' || p_buscar || '%'
           OR c.nombre ILIKE '%' || p_buscar || '%'
        ORDER BY c.nombre
        LIMIT 200;
END
$fn$;

CREATE OR REPLACE FUNCTION app_registrar_cliente(p_token UUID, p_nit TEXT, p_nombre TEXT,
        p_direccion TEXT DEFAULT '', p_telefono TEXT DEFAULT '') RETURNS JSON
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
DECLARE
    v_nit TEXT := trim(coalesce(p_nit, ''));
    v_id INTEGER;
BEGIN
    PERFORM app_usuario_de(p_token);
    IF regexp_replace(v_nit, '[- ]', '', 'g') !~ '^[0-9]{8,13}$' THEN
        RAISE EXCEPTION 'El NIT debe tener entre 8 y 13 dígitos.' USING ERRCODE = '22023';
    END IF;
    IF trim(coalesce(p_nombre, '')) = '' THEN
        RAISE EXCEPTION 'Escriba el nombre del cliente.' USING ERRCODE = '22023';
    END IF;
    IF EXISTS (SELECT 1 FROM clientes WHERE nit = v_nit) THEN
        RAISE EXCEPTION 'Ya existe un cliente con ese NIT.' USING ERRCODE = '23505';
    END IF;
    INSERT INTO clientes (nit, nombre, direccion, telefono)
    VALUES (v_nit, trim(p_nombre), trim(coalesce(p_direccion, '')), trim(coalesce(p_telefono, '')))
    RETURNING id INTO v_id;
    RETURN json_build_object('id', v_id, 'nit', v_nit, 'nombre', trim(p_nombre));
END
$fn$;

CREATE OR REPLACE FUNCTION app_ventas(p_token UUID, p_desde DATE, p_hasta DATE)
RETURNS TABLE (numero_factura TEXT, fecha DATE, cliente TEXT, total NUMERIC)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
#variable_conflict use_column
BEGIN
    PERFORM app_usuario_de(p_token);
    RETURN QUERY
        SELECT f.numero_factura, left(f.fecha, 10)::DATE, f.cliente, f.total
        FROM facturas f
        WHERE left(f.fecha, 10)::DATE BETWEEN p_desde AND p_hasta
        ORDER BY f.id DESC;
END
$fn$;

-- Productos de una factura (pantalla de detalle de venta del movil).
CREATE OR REPLACE FUNCTION app_detalle_venta(p_token UUID, p_numero_factura TEXT)
RETURNS TABLE (producto TEXT, cantidad INTEGER, precio NUMERIC, subtotal NUMERIC)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
#variable_conflict use_column
BEGIN
    PERFORM app_usuario_de(p_token);
    RETURN QUERY
        SELECT d.producto, d.cantidad, d.precio, d.subtotal
        FROM factura_detalles d JOIN facturas f ON f.id = d.factura_id
        WHERE f.numero_factura = p_numero_factura
        ORDER BY d.id;
END
$fn$;

-- Datos del tablero "Resumen" en una sola llamada. p_hoy lo envia el telefono
-- (fecha local); el servidor trabaja en UTC y su "hoy" podria ser otro dia.
CREATE OR REPLACE FUNCTION app_resumen(p_token UUID, p_hoy DATE, p_existencia_baja INTEGER DEFAULT 5)
RETURNS JSON
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
DECLARE
    v_inicio_mes DATE := date_trunc('month', p_hoy)::DATE;
BEGIN
    PERFORM app_usuario_de(p_token);
    RETURN json_build_object(
        'ventas_hoy', (SELECT coalesce(sum(total), 0) FROM facturas WHERE left(fecha, 10)::DATE = p_hoy),
        'facturas_hoy', (SELECT count(*) FROM facturas WHERE left(fecha, 10)::DATE = p_hoy),
        'ventas_mes', (SELECT coalesce(sum(total), 0) FROM facturas
                       WHERE left(fecha, 10)::DATE BETWEEN v_inicio_mes AND p_hoy),
        'ventas_7_dias', (
            SELECT json_agg(json_build_object('fecha', dia::DATE, 'total', coalesce(v.total, 0)) ORDER BY dia)
            FROM generate_series(p_hoy - 6, p_hoy, INTERVAL '1 day') AS dia
            LEFT JOIN (SELECT left(fecha, 10)::DATE AS f, sum(total) AS total FROM facturas GROUP BY 1) v
                   ON v.f = dia::DATE),
        'top_productos', coalesce((
            SELECT json_agg(t) FROM (
                SELECT d.producto, sum(d.cantidad) AS cantidad, sum(d.subtotal) AS total
                FROM factura_detalles d JOIN facturas f ON f.id = d.factura_id
                WHERE left(f.fecha, 10)::DATE BETWEEN v_inicio_mes AND p_hoy
                GROUP BY d.producto
                ORDER BY sum(d.cantidad) DESC, d.producto
                LIMIT 5) t), '[]'::JSON),
        'existencia_baja', coalesce((
            SELECT json_agg(b) FROM (
                SELECT codigo, nombre, existencia FROM productos
                WHERE existencia <= p_existencia_baja
                ORDER BY existencia, nombre
                LIMIT 20) b), '[]'::JSON)
    );
END
$fn$;

-- Factura desde el movil, en UNA transaccion (la funcion completa se revierte si algo falla):
-- numero correlativo, detalles con el precio de la base (no el que envia el telefono)
-- y descuento de existencia; si un producto no alcanza, no se guarda nada.
-- p_detalles: [{"codigo": "P-1", "cantidad": 2}, ...]
CREATE OR REPLACE FUNCTION app_registrar_factura(p_token UUID, p_nit TEXT, p_cliente TEXT,
        p_fecha DATE, p_detalles JSON) RETURNS JSON
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
DECLARE
    v_nit TEXT := trim(coalesce(p_nit, ''));
    v_cliente TEXT := trim(coalesce(p_cliente, ''));
    v_numero TEXT;
    v_factura_id INTEGER;
    v_total NUMERIC(12, 2) := 0;
    v_linea JSON;
    v_cantidad INTEGER;
    v_producto productos%ROWTYPE;
BEGIN
    PERFORM app_usuario_de(p_token);
    IF regexp_replace(v_nit, '[- ]', '', 'g') !~ '^[0-9]{8,13}$' THEN
        RAISE EXCEPTION 'El NIT debe tener entre 8 y 13 dígitos.' USING ERRCODE = '22023';
    END IF;
    IF v_cliente = '' THEN
        RAISE EXCEPTION 'Escriba el nombre del cliente.' USING ERRCODE = '22023';
    END IF;
    IF p_detalles IS NULL OR json_array_length(p_detalles) = 0 THEN
        RAISE EXCEPTION 'Agregue al menos un producto.' USING ERRCODE = '22023';
    END IF;
    IF (SELECT count(DISTINCT lower(l ->> 'codigo')) FROM json_array_elements(p_detalles) l)
            <> json_array_length(p_detalles) THEN
        RAISE EXCEPTION 'Hay un producto repetido en la factura.' USING ERRCODE = '22023';
    END IF;

    -- evita que dos ventas simultaneas obtengan el mismo numero de factura
    LOCK TABLE facturas IN SHARE ROW EXCLUSIVE MODE;
    SELECT 'FAC-' || lpad((coalesce(max(substring(numero_factura FROM '([0-9]+)$')::INTEGER), 0) + 1)::TEXT, 4, '0')
      INTO v_numero FROM facturas;

    INSERT INTO facturas (numero_factura, nit, cliente, fecha, total)
    VALUES (v_numero, v_nit, v_cliente, to_char(coalesce(p_fecha, CURRENT_DATE), 'YYYY-MM-DD') || ' 00:00:00', 0)
    RETURNING id INTO v_factura_id;

    FOR v_linea IN SELECT * FROM json_array_elements(p_detalles) LOOP
        v_cantidad := (v_linea ->> 'cantidad')::INTEGER;
        IF v_cantidad IS NULL OR v_cantidad <= 0 THEN
            RAISE EXCEPTION 'La cantidad debe ser mayor que 0.' USING ERRCODE = '22023';
        END IF;
        SELECT * INTO v_producto FROM productos WHERE lower(codigo) = lower(v_linea ->> 'codigo') FOR UPDATE;
        IF v_producto.id IS NULL THEN
            RAISE EXCEPTION 'El producto % no existe.', v_linea ->> 'codigo' USING ERRCODE = '22023';
        END IF;
        IF v_producto.existencia < v_cantidad THEN
            RAISE EXCEPTION 'No hay existencia suficiente de % (quedan %).', v_producto.nombre, v_producto.existencia
                USING ERRCODE = '22023';
        END IF;
        UPDATE productos SET existencia = existencia - v_cantidad WHERE id = v_producto.id;
        INSERT INTO factura_detalles (factura_id, producto, cantidad, precio, subtotal, producto_id)
        VALUES (v_factura_id, v_producto.nombre, v_cantidad, v_producto.precio, v_cantidad * v_producto.precio, v_producto.id);
        v_total := v_total + v_cantidad * v_producto.precio;
    END LOOP;

    UPDATE facturas SET total = v_total WHERE id = v_factura_id;
    RETURN json_build_object('numero_factura', v_numero, 'total', v_total);
END
$fn$;

-- Por defecto cualquiera puede ejecutar funciones: se deja solo lo necesario.
REVOKE ALL ON FUNCTION app_detalle_venta(UUID, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_resumen(UUID, DATE, INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_registrar_factura(UUID, TEXT, TEXT, DATE, JSON) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_usuario_de(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_login(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_logout(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_productos(UUID, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_clientes(UUID, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_registrar_cliente(UUID, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_ventas(UUID, DATE, DATE) FROM PUBLIC;

DO $bloque$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON FUNCTION app_usuario_de(UUID) FROM anon, authenticated;
        GRANT EXECUTE ON FUNCTION app_login(TEXT, TEXT) TO anon, authenticated;
        GRANT EXECUTE ON FUNCTION app_logout(UUID) TO anon, authenticated;
        GRANT EXECUTE ON FUNCTION app_productos(UUID, TEXT) TO anon, authenticated;
        GRANT EXECUTE ON FUNCTION app_clientes(UUID, TEXT) TO anon, authenticated;
        GRANT EXECUTE ON FUNCTION app_registrar_cliente(UUID, TEXT, TEXT, TEXT, TEXT) TO anon, authenticated;
        GRANT EXECUTE ON FUNCTION app_ventas(UUID, DATE, DATE) TO anon, authenticated;
        GRANT EXECUTE ON FUNCTION app_detalle_venta(UUID, TEXT) TO anon, authenticated;
        GRANT EXECUTE ON FUNCTION app_resumen(UUID, DATE, INTEGER) TO anon, authenticated;
        GRANT EXECUTE ON FUNCTION app_registrar_factura(UUID, TEXT, TEXT, DATE, JSON) TO anon, authenticated;
    END IF;
END
$bloque$;
